"""Strict ledger-level ablations for the locked PRQ-Net/BCR-Net CDEL fusion."""

from neuroez_c.p2_v3_conservative_fusion import LOCKED_P2_WEIGHT, LOCKED_V3_WEIGHT
LOCKED_STATUS = "EXPLORATORY_LOCKED_FUSION"
ABLATION_STATUS = "ABLATION_ONLY_NOT_FOR_MODEL_SELECTION"
DIAGNOSTIC_STATUS = "DIAGNOSTIC_ONLY_NOT_DEPLOYABLE"
