from __future__ import annotations
import argparse,json,os,sys,time,copy
from pathlib import Path
import pandas as pd,torch,numpy as np
PROJECT=Path(__file__).resolve().parents[2];sys.path[:0]=[str(PROJECT),str(PROJECT.parent)]
from neuroez_c.task2.data import load_cache,filtered_cache
from neuroez_c.task2.exclusions import load_exclusion_manifest
from neuroez_c.task2.outcomes import load_outcome_table
from neuroez_c.task2.protocol import load_fold_manifest,manifest_patient_keys
from neuroez_c.task2.tech_outcome_c1 import MODEL_VERSION,PROTOCOL
from neuroez_c.task2.tech_outcome_c1.schema import ViewConfig,validate_patient
from neuroez_c.task2.tech_outcome_c1.cache import build_cache
from neuroez_c.task2.tech_outcome_c1.data import CachedCohort
from neuroez_c.task2.tech_outcome_c1.model import TeChOutcomeC1
from neuroez_c.task2.tech_outcome_c1.split import development_split,assert_isolated
from neuroez_c.task2.tech_outcome_c1.trainer import train_epoch,infer
from neuroez_c.task2.tech_outcome_c1.evaluation import metrics,bootstrap,assert_oof
from neuroez_c.task2.tech_outcome_c1.audit import protocol_audit
from neuroez_c.task2.tech_outcome_c1.progress import tqdm

def parse():
 p=argparse.ArgumentParser();e=os.getenv
 for name,env in [('raw_cache','DRE_TASK1_RAW_CACHE_PATH'),('outcome_table','DRE_TASK2_OUTCOME_TABLE'),('fold_manifest','DRE_TASK2_FOLD_MANIFEST'),('exclusion_manifest','DRE_TASK2_EXCLUSION_MANIFEST'),('cache_dir','DRE_TASK2_TECH_C1_CACHE_DIR'),('output_dir','DRE_TASK2_TECH_C1_OUTPUT_DIR')]:p.add_argument('--'+name.replace('_','-'),'--'+name,dest=name,default=e(env),required=e(env) is None)
 p.add_argument('--seed',type=int,default=42);p.add_argument('--folds',default='all');p.add_argument('--device',default='cuda');p.add_argument('--d-model',type=int,default=64);p.add_argument('--d-core',type=int,default=16);p.add_argument('--cotar-layers',type=int,default=2);p.add_argument('--dropout',type=float,default=.1);p.add_argument('--batch-size',type=int,default=4);p.add_argument('--gradient-accumulation-steps',type=int,default=2);p.add_argument('--learning-rate',type=float,default=1e-4);p.add_argument('--weight-decay',type=float,default=1e-3);p.add_argument('--max-epochs',type=int,default=30);p.add_argument('--min-epochs',type=int,default=5);p.add_argument('--patience',type=int,default=5);p.add_argument('--min-delta',type=float,default=1e-4);p.add_argument('--validation-fraction',type=float,default=.2);p.add_argument('--max-seizures-train',type=int,default=3);p.add_argument('--max-channels-train',type=int,default=96);p.add_argument('--max-windows-per-phase-train',type=int,default=6);p.add_argument('--encoder-window-batch-size-train',type=int,default=1024);p.add_argument('--encoder-window-batch-size-eval',type=int,default=4096);p.add_argument('--amp',action=argparse.BooleanOptionalAction,default=True);p.add_argument('--amp-dtype',choices=['bf16','fp16'],default='bf16');p.add_argument('--show-progress',dest='show_progress',action='store_true',default=True);p.add_argument('--no-progress',dest='show_progress',action='store_false');p.add_argument('--print-val-auroc',action='store_true',default=True);p.add_argument('--disable-augmentations',action='store_true');p.add_argument('--verify-cache-only',action='store_true');p.add_argument('--overfit-audit',action='store_true');p.add_argument('--smoke-test',action='store_true');p.add_argument('--strict',action='store_true');return p.parse_args()
def write_json(path,value):path=Path(path);path.parent.mkdir(parents=True,exist_ok=True);path.write_text(json.dumps(value,indent=2,default=str),encoding='utf8')
def write_csv(path,frame):path=Path(path);path.parent.mkdir(parents=True,exist_ok=True);frame.to_csv(path,index=False)
def checkpoint(model,opt,fold,epoch,val,kind):return {'model_version':MODEL_VERSION,'protocol':PROTOCOL,'outer_fold':int(fold),'selected_epoch':epoch,'best_validation_bce':val['bce'],'best_validation_auroc':val['auroc'],'selection_metric':kind,'model_state_dict':model.state_dict(),'optimizer_state_dict':opt.state_dict()}
def overfit_audit(a,out,cohort,labels,device):
    success=[k for k in cohort.paths if labels[k]==1][:4];failure=[k for k in cohort.paths if labels[k]==0][:4];keys=success+failure
    if len(success)!=4 or len(failure)!=4:raise RuntimeError('overfit audit requires 4 success and 4 failure patients')
    model=TeChOutcomeC1(a.d_model,a.d_core,a.cotar_layers,a.dropout).to(device);model.augmentations_enabled=False
    for module in model.modules():
        if isinstance(module,torch.nn.Dropout):module.p=0
    optimizer=torch.optim.AdamW(model.parameters(),lr=a.learning_rate,weight_decay=0);old_progress=a.show_progress;a.show_progress=False;passed=False;last={}
    for epoch in tqdm(range(1,301),desc='TECH-C1 8-patient overfit',disable=not old_progress):
        train_epoch(model,cohort,keys,labels,optimizer,device,epoch,a);frame,_,_,_=infer(model,cohort,keys,labels,0,a,'overfit inference');m=metrics(frame);bce=float(-np.mean(frame.outcome_true*np.log(np.clip(frame.probability_success,1e-7,1-1e-7))+(1-frame.outcome_true)*np.log(np.clip(1-frame.probability_success,1e-7,1-1e-7))));last={'epoch':epoch,'train_accuracy':m['accuracy'],'train_auroc':m['auroc'],'train_bce':bce,'probability_std':m['probability_std']};passed=m['accuracy']>=.95 and m['auroc']>=.98 and bce<=.10 and m['probability_std']>.20
        if passed:break
    a.show_progress=old_progress;result={'passed':passed,'n_patients':8,**last};write_json(out/'audit/overfit_audit.json',result)
    if a.strict and not passed:raise RuntimeError(f'8-patient overfit audit failed: {result}')
    return 0
def main():
 a=parse();torch.manual_seed(a.seed);device=torch.device(a.device if a.device!='cuda' or torch.cuda.is_available() else 'cpu');a.amp=bool(a.amp and device.type=='cuda');out=Path(a.output_dir)
 if a.strict and (a.d_model!=64 or a.d_core!=16 or a.cotar_layers!=2 or abs(a.dropout-.10)>1e-12 or a.batch_size!=4 or a.gradient_accumulation_steps!=2 or abs(a.learning_rate-1e-4)>1e-15 or abs(a.weight_decay-1e-3)>1e-15 or a.max_epochs!=30 or a.min_epochs!=5 or a.patience!=5 or abs(a.min_delta-1e-4)>1e-15 or abs(a.validation_fraction-.20)>1e-15 or a.max_seizures_train!=3 or a.max_channels_train!=96 or a.max_windows_per_phase_train!=6):raise ValueError('strict TECH_OUTCOME_C1 requires the fixed C1 architecture and training protocol')
 for name in ('audit','checkpoints','splits','predictions','metrics','embeddings','logs','reports','runtime'): (out/name).mkdir(parents=True,exist_ok=True)
 started=time.time();write_json(out/'audit/third_party_code_audit.json',{'reference_repository':'Levi-Ackman/TeCh','reference_commit':'9a378cc546a5d97c871eff282148175b3c7cd75b','license_detected':False,'source_code_copied':False,'mathematical_behavior_reimplemented':True});write_json(out/'audit/tech_c1_protocol_audit.json',protocol_audit());write_json(out/'audit/no_task1_dependency_audit.json',{'uses_task1':False});write_json(out/'audit/no_ez_nez_usage_audit.json',{'uses_ez_nez_labels':False,'forbidden_field_in_model_batch':False})
 source=load_cache(a.raw_cache);filtered=filtered_cache(source,load_exclusion_manifest(a.exclusion_manifest));outcomes,_=load_outcome_table(a.outcome_table,cache=filtered);outcomes=outcomes[outcomes.outcome_group.isin(['success','failure'])];labels=outcomes.set_index('patient_key').outcome_label.astype(int).to_dict();cache_dir=Path(a.cache_dir)
 if not (cache_dir/'cache_manifest.csv').exists():build_cache(filtered['run_records'],labels,cache_dir)
 cohort=CachedCohort(cache_dir,a.seed,ViewConfig(a.max_seizures_train,a.max_channels_train,a.max_windows_per_phase_train));meta={k:cohort.load(k) for k in cohort.paths}
 try:
  for patient in meta.values():validate_patient(patient)
  cache_has_ez=any('channel_labels_nez' in seizure for patient in meta.values() for seizure in patient['seizures']);sample_view=cohort.view(next(iter(meta)),0,False);write_json(out/'audit/cache_validation_audit.json',{'valid':True,'n_patients':len(meta),'cache_contains_channel_labels_nez':cache_has_ez,'formal_view_contains_channel_labels_nez':'channel_labels_nez' in str(sample_view)})
 except Exception as exc:write_json(out/'audit/cache_validation_audit.json',{'valid':False,'error':str(exc)});raise
 if a.verify_cache_only:return 0
 fold_frame=load_fold_manifest(a.fold_manifest,outcomes,strict=a.strict);expected=set(manifest_patient_keys(a.fold_manifest))
 if a.strict and set(meta)!=expected:raise RuntimeError('TeCh-C1 cache does not exactly cover fixed fold manifest')
 model0=TeChOutcomeC1(a.d_model,a.d_core,a.cotar_layers,a.dropout);write_json(out/'audit/tech_c1_model_audit.json',{'model_version':MODEL_VERSION,'parameter_count':model0.parameter_count(),'d_model':a.d_model,'d_core':a.d_core,'n_cotar_layers':a.cotar_layers,'uses_batch_norm':False});del model0
 if a.overfit_audit:return overfit_audit(a,out,cohort,labels,device)
 if a.strict and not a.smoke_test:
  gate=out/'audit/overfit_audit.json'
  if not gate.exists() or not json.loads(gate.read_text()).get('passed'):raise RuntimeError('strict five-fold run requires a passing --overfit-audit in this output directory')
 requested=sorted(fold_frame.outer_fold.unique()) if a.folds=='all' else [int(x) for x in a.folds.split(',')];history=[];all_predictions=[];fold_rows=[];split_path=out/'splits/outer_split_audit.csv';split_rows=pd.read_csv(split_path).to_dict('records') if split_path.exists() else [];core_rows=[];seizure_rows=[];patient_rows=[];fit_rows=[];split_json=[]
 for fold in tqdm(requested,desc='TECH-C1 outer folds',disable=not a.show_progress):
  test=fold_frame.loc[fold_frame.outer_fold==fold,'patient_key'].tolist();development=[k for k in meta if k not in set(test)];old=pd.DataFrame(split_rows);train,val=development_split(development,meta,fold,a.seed,a.validation_fraction,old);assert_isolated(train,val,test);split_json.append({'outer_fold':int(fold),'development_train':train,'development_validation':val,'outer_test':test});split_rows=[row for row in split_rows if int(row['outer_fold'])!=int(fold)];split_rows += [{'patient_key':k,'outer_fold':fold,'partition':'development_train','outcome':labels[k],'center':meta[k]['center']} for k in train]+[{'patient_key':k,'outer_fold':fold,'partition':'development_validation','outcome':labels[k],'center':meta[k]['center']} for k in val]+[{'patient_key':k,'outer_fold':fold,'partition':'outer_test','outcome':labels[k],'center':meta[k]['center']} for k in test];write_csv(split_path,pd.DataFrame(split_rows))
  torch.manual_seed(a.seed+int(fold));model=TeChOutcomeC1(a.d_model,a.d_core,a.cotar_layers,a.dropout).to(device);model.augmentations_enabled=not a.disable_augmentations;opt=torch.optim.AdamW(model.parameters(),lr=a.learning_rate,weight_decay=a.weight_decay);best_bce=float('inf');best_auc=-float('inf');best_epoch=0;wait=0;cp=out/'checkpoints'/f'fold_{fold}';cp.mkdir(parents=True,exist_ok=True);epochs=2 if a.smoke_test else a.max_epochs
  for epoch in tqdm(range(1,epochs+1),desc=f'Fold {fold} epochs',disable=not a.show_progress):
   train_stats=train_epoch(model,cohort,train,labels,opt,device,epoch,a);val_frame,_,_,_=infer(model,cohort,val,labels,fold,a,f'Validate fold {fold}');val_metrics=metrics(val_frame);saved=val_metrics['brier']<float('inf') and val_metrics.get('n_patients',0)>0 and (-np.mean(val_frame.outcome_true*np.log(np.clip(val_frame.probability_success,1e-7,1-1e-7))+(1-val_frame.outcome_true)*np.log(np.clip(1-val_frame.probability_success,1e-7,1-1e-7))))<best_bce-a.min_delta;val_bce=float(-np.mean(val_frame.outcome_true*np.log(np.clip(val_frame.probability_success,1e-7,1-1e-7))+(1-val_frame.outcome_true)*np.log(np.clip(1-val_frame.probability_success,1e-7,1-1e-7))))
   if saved:best_bce=val_bce;best_epoch=epoch;wait=0;torch.save(checkpoint(model,opt,fold,epoch,{'bce':val_bce,'auroc':val_metrics['auroc']},'validation_bce'),cp/'best_val_bce.pt')
   else:wait+=1
   if np.isfinite(val_metrics['auroc']) and val_metrics['auroc']>best_auc:best_auc=val_metrics['auroc'];torch.save(checkpoint(model,opt,fold,epoch,{'bce':val_bce,'auroc':best_auc},'validation_auroc_diagnostic'),cp/'best_val_auroc.pt')
   row={'outer_fold':fold,'epoch':epoch,**train_stats,'val_bce':val_bce,**{f'val_{k}':v for k,v in val_metrics.items()},'best_val_bce':best_bce,'best_val_auroc':best_auc,'best_epoch':best_epoch,'patience_counter':wait,'checkpoint_saved':saved,'learning_rate':a.learning_rate};history.append(row);message=f'[TECH-C1] fold={fold} epoch={epoch}/{epochs} train_bce={train_stats["train_bce"]:.6f} train_auroc={train_stats["train_auroc"]} val_bce={val_bce:.6f} val_auroc={val_metrics["auroc"]} val_failure_auprc={val_metrics["failure_auprc"]} val_balanced_accuracy={val_metrics["balanced_accuracy"]} val_macro_f1={val_metrics["macro_f1"]} val_p_mean={val_metrics["probability_mean"]:.6f} val_p_std={val_metrics["probability_std"]:.6f} best_val_bce={best_bce:.6f} best_val_auroc={best_auc} best_epoch={best_epoch} patience={wait}/{a.patience} checkpoint_saved={"yes" if saved else "no"}';tqdm.write(message);print(message,flush=True)
   if epoch>=a.min_epochs and wait>=a.patience:break
  chosen=torch.load(cp/'best_val_bce.pt',map_location=device,weights_only=False);model.load_state_dict(chosen['model_state_dict']);train_fit,_,_,_=infer(model,cohort,train,labels,fold,a,f'Fit audit train fold {fold}');val_fit,_,_,_=infer(model,cohort,val,labels,fold,a,f'Fit audit validation fold {fold}');test_frame,cores,seizures,patients=infer(model,cohort,test,labels,fold,a,f'Final test fold {fold}')
  for name,frame in [('development_train',train_fit),('development_validation',val_fit),('outer_test',test_frame)]:fit_rows.append({'outer_fold':fold,'split':name,**metrics(frame)})
  test_frame['outer_fold']=fold;test_frame['selected_epoch']=chosen['selected_epoch'];test_frame['best_validation_bce']=chosen['best_validation_bce'];test_frame['best_validation_auroc']=best_auc;all_predictions.extend(test_frame.to_dict('records'));core_rows.extend(cores.to_dict('records'));seizure_rows.extend(seizures.to_dict('records'));patient_rows.extend(patients.to_dict('records'));fold_rows.append({'outer_fold':fold,'selected_epoch':chosen['selected_epoch'],'best_validation_bce':chosen['best_validation_bce'],'best_validation_auroc':best_auc,**metrics(test_frame)})
  if device.type=='cuda':torch.cuda.empty_cache()
 predictions=pd.DataFrame(all_predictions);assert_oof(predictions,len(meta) if a.folds=='all' else None)
 if a.folds=='all' and len(fold_rows)!=5:raise RuntimeError('formal five-fold metrics must have five rows')
 write_csv(out/'splits/outer_split_audit.csv',pd.DataFrame(split_rows));write_json(out/'splits/development_splits.json',split_json);write_csv(out/'metrics/training_history.csv',pd.DataFrame(history));write_csv(out/'metrics/validation_epoch_metrics.csv',pd.DataFrame(history));write_csv(out/'metrics/fold_metrics.csv',pd.DataFrame(fold_rows));write_csv(out/'metrics/summary_metrics.csv',pd.DataFrame([metrics(predictions)]));write_csv(out/'metrics/bootstrap_ci.csv',bootstrap(predictions,2000,a.seed));write_csv(out/'metrics/metrics_by_center.csv',pd.DataFrame([{'center':c,**metrics(g)} for c,g in predictions.groupby('center')]));write_csv(out/'metrics/fit_generalization_audit.csv',pd.DataFrame(fit_rows));write_csv(out/'predictions/oof_patient_predictions.csv',predictions);write_csv(out/'predictions/misclassified_patients.csv',predictions[predictions.outcome_true!=predictions.prediction_05]);write_csv(out/'predictions/seizure_predictions.csv',pd.DataFrame(seizure_rows));write_csv(out/'embeddings/channel_core_audit.csv',pd.DataFrame(core_rows));write_csv(out/'embeddings/seizure_embedding_audit.csv',pd.DataFrame(seizure_rows));write_csv(out/'embeddings/patient_embedding_audit.csv',pd.DataFrame(patient_rows));(out/'logs/training_console.log').write_text('\n'.join(f"fold={x['outer_fold']} epoch={x['epoch']} val_auroc={x['val_auroc']} val_bce={x['val_bce']}" for x in history),encoding='utf8');write_json(out/'runtime/runtime_profile.json',{'wall_time_seconds':time.time()-started,'device':str(device),'amp':a.amp});(out/'reports/TECH_OUTCOME_C1_REPORT.md').write_text('# TECH_OUTCOME_C1\n\nIndependent masked centralized-core patient outcome model. Final checkpoint monitor: validation BCE.\n',encoding='utf8');return 0
if __name__=='__main__':raise SystemExit(main())
