"""TRACE_RAWMIL_CLEAN_V1: validation-AUROC selected, EMA-evaluated outer CV."""
from __future__ import annotations
import argparse, hashlib, json, os, sys, time
from pathlib import Path
import numpy as np, pandas as pd, torch
from sklearn.model_selection import StratifiedShuffleSplit
from tqdm.auto import tqdm
PROJECT=Path(__file__).resolve().parents[2]; sys.path[:0]=[str(PROJECT),str(PROJECT.parent)]
from neuroez_c.task2.data import load_cache,filtered_cache
from neuroez_c.task2.exclusions import load_exclusion_manifest
from neuroez_c.task2.outcomes import load_outcome_table
from neuroez_c.task2.protocol import load_fold_manifest,manifest_patient_keys
from neuroez_c.task2.trace_rawmil.raw_dataset import build_patients
from neuroez_c.task2.trace_rawmil.raw_dataset import patient_tensors
from neuroez_c.task2.trace_rawmil.model import TRACERawMIL
from neuroez_c.task2.trace_rawmil.trainer import seed_all,train_epoch,infer,ModelEMA,validation_statistics,better_checkpoint
from neuroez_c.task2.trace_rawmil.evaluation import metric_row,bootstrap_ci
from neuroez_c.task2.trace_rawmil.losses import trace_loss,rank_weight

MODEL='TRACE_RAWMIL_CLEAN_V1'
def parse():
 p=argparse.ArgumentParser(); env=os.getenv
 for k,e in [('raw_cache','DRE_TASK1_RAW_CACHE_PATH'),('outcome_table','DRE_TASK2_OUTCOME_TABLE'),('fold_manifest','DRE_TASK2_FOLD_MANIFEST'),('exclusion_manifest','DRE_TASK2_EXCLUSION_MANIFEST'),('output_dir','DRE_TASK2_TRACE_CLEAN_V1_OUTPUT_DIR')]: p.add_argument('--'+k, '--'+k.replace('_','-'),dest=k,default=env(e),required=env(e) is None)
 p.add_argument('--seed',type=int,default=42);p.add_argument('--folds',default='all');p.add_argument('--device',default='cuda' if torch.cuda.is_available() else 'cpu');p.add_argument('--batch-size',type=int,default=4);p.add_argument('--max-epochs',type=int,default=15);p.add_argument('--patience',type=int,default=3);p.add_argument('--min-delta',type=float,default=1e-6);p.add_argument('--learning-rate',type=float,default=3e-4);p.add_argument('--weight-decay',type=float,default=1e-3);p.add_argument('--gradient-clip-norm',type=float,default=1.0);p.add_argument('--gradient-accumulation-steps',type=int,default=2);p.add_argument('--ema-decay',type=float,default=.995);p.add_argument('--validation-fraction',type=float,default=.2);p.add_argument('--encoder-window-batch-size-train',type=int,default=1024);p.add_argument('--encoder-window-batch-size-eval',type=int,default=4096);p.add_argument('--gradient-checkpoint-encoder',action=argparse.BooleanOptionalAction,default=True);p.add_argument('--auto-window-batch-backoff',action=argparse.BooleanOptionalAction,default=True);p.add_argument('--min-window-batch-size',type=int,default=128);p.add_argument('--vram-budget-fraction',type=float,default=.75);p.add_argument('--max-seizures-train',type=int,default=2);p.add_argument('--max-ez-channels-train',type=int,default=24);p.add_argument('--max-nez-channels-train',type=int,default=32);p.add_argument('--max-windows-per-phase-train',type=int,default=4);p.add_argument('--show-progress',dest='show_progress',action='store_true',default=True);p.add_argument('--no-progress',dest='show_progress',action='store_false');p.add_argument('--resume',action=argparse.BooleanOptionalAction,default=True);p.add_argument('--strict',action='store_true'); return p.parse_args()
def write_csv(path,frame): Path(path).parent.mkdir(parents=True,exist_ok=True);frame.to_csv(path,index=False)
def split(train,fold,a,existing):
 by={p.patient_key:p for p in train}; old=existing[(existing.outer_fold==fold)] if not existing.empty else pd.DataFrame()
 if not old.empty and set(old.patient_key)==set(by) and set(old.partition)=={'inner_train','inner_validation'}:
  return [by[k] for k in old.loc[old.partition=='inner_train','patient_key']],[by[k] for k in old.loc[old.partition=='inner_validation','patient_key']]
 labels=np.asarray([x.outcome_success for x in train]); groups=np.asarray([f'{x.center}|{x.outcome_success}' for x in train]); strata=groups if min((groups==g).sum() for g in set(groups))>=2 else labels
 try: i,j=next(StratifiedShuffleSplit(1,test_size=a.validation_fraction,random_state=a.seed+int(fold)).split(np.zeros(len(train)),strata))
 except ValueError: i,j=next(StratifiedShuffleSplit(1,test_size=a.validation_fraction,random_state=a.seed+int(fold)).split(np.zeros(len(train)),labels))
 return [train[x] for x in i],[train[x] for x in j]
def autotune(probe,patients,device,a,fold_seed):
 if device.type!='cuda': return a.encoder_window_batch_size_train
 sample=patients[:min(4,len(patients))];tensors=[patient_tensors(p,'cpu',np.random.default_rng(fold_seed*100000+i),a.max_seizures_train,a.max_ez_channels_train,a.max_nez_channels_train,a.max_windows_per_phase_train) for i,p in enumerate(sample)];selected=a.min_window_batch_size;total=torch.cuda.get_device_properties(device).total_memory
 for size in (256,512,1024,2048):
  try:
   torch.cuda.empty_cache();torch.cuda.reset_peak_memory_stats(device);probe.zero_grad(set_to_none=True);probe.configure_encoder(size,a.gradient_checkpoint_encoder,True);outputs=probe(tensors);loss,_=trace_loss(outputs,[p.outcome_success for p in sample],1);loss.backward();reserved=torch.cuda.max_memory_reserved(device)
   if reserved<total*a.vram_budget_fraction:selected=size
  except (RuntimeError,torch.cuda.OutOfMemoryError) as exc:
   if 'out of memory' not in str(exc).lower(): raise
   torch.cuda.empty_cache();break
 return selected
def state(model,opt,fold,a,best_epoch,best_auc,best_bce,v,manifest_hash):
 return {'model_version':MODEL,'outer_fold':int(fold),'seed':a.seed,'best_epoch':best_epoch,'best_val_auroc':best_auc,'best_val_bce':best_bce,'best_val_rank':v['validation_rank'],'best_val_selection':v['validation_selection_loss'],'ema_decay':a.ema_decay,'model_state_dict':model.state_dict(),'optimizer_state_dict':opt.state_dict(),'validation_manifest_hash':manifest_hash,'config_hash':hashlib.sha256(json.dumps(vars(a),sort_keys=True,default=str).encode()).hexdigest()}
def main():
 a=parse();seed_all(a.seed);out=Path(a.output_dir);out.mkdir(parents=True,exist_ok=True);device=torch.device(a.device);a.current_train_window_batch_size=a.encoder_window_batch_size_train;a.current_eval_window_batch_size=a.encoder_window_batch_size_eval
 if a.strict and (a.max_epochs!=15 or a.patience!=3 or abs(a.min_delta-1e-6)>1e-15 or abs(a.learning_rate-3e-4)>1e-15 or abs(a.weight_decay-1e-3)>1e-15 or a.batch_size!=4 or a.gradient_accumulation_steps!=2 or abs(a.gradient_clip_norm-1.0)>1e-15 or abs(a.ema_decay-.995)>1e-15 or abs(a.validation_fraction-.20)>1e-15 or a.max_seizures_train!=2 or a.max_ez_channels_train!=24 or a.max_nez_channels_train!=32 or a.max_windows_per_phase_train!=4): raise ValueError('strict TRACE-CLEAN-V1 requires the fixed optimizer/EMA/sampling/early-stopping configuration')
 cache=filtered_cache(load_cache(a.raw_cache),load_exclusion_manifest(a.exclusion_manifest)); outcomes,_=load_outcome_table(a.outcome_table,cache=cache);outcomes=outcomes[outcomes.outcome_group.isin(['success','failure'])];folds=load_fold_manifest(a.fold_manifest,outcomes,strict=a.strict);labels=outcomes.set_index('patient_key').outcome_label.astype(int).to_dict();patients,_=build_patients(cache['run_records'],labels);by={p.patient_key:p for p in patients};patients=[by[k] for k in manifest_patient_keys(a.fold_manifest) if k in by]
 if a.strict and len(patients)!=len(folds): raise ValueError('raw-valid cohort does not match fixed manifest')
 wanted=sorted(folds.outer_fold.unique()) if a.folds=='all' else [int(x) for x in a.folds.split(',')];history=[];oof=[];summaries=[];manifest_path=out/'trace_inner_validation_manifest.csv';existing=pd.read_csv(manifest_path) if a.resume and manifest_path.exists() else pd.DataFrame(columns=['patient_key','outer_fold','partition','outcome','center']);inner=existing.to_dict('records')
 protocol={'model_version':MODEL,'model_structure':'TRACE_RAWMIL_V1','uses_task1':False,'uses_true_ez_nez_mask':True,'uses_channel_auxiliary_loss':False,'loss':'BCE_PLUS_WEAK_BATCH_RANK','rank_schedule':'epoch_1_to_5_zero_then_linear_0p15_over_15_epochs','patient_sampler':'without_replacement','each_patient_once_per_epoch':True,'uses_class_weight':False,'uses_ranking_queue':False,'learning_rate':a.learning_rate,'uses_lr_scheduler':False,'ema_decay':a.ema_decay,'max_epochs':a.max_epochs,'early_stopping_monitor':'validation_auroc','early_stopping_mode':'max','early_stopping_patience':a.patience,'validation_fraction':a.validation_fraction,'requires_historical_patient_identity_match':False,'validation_is_deterministic':True,'outer_test_used_for_training':False,'outer_test_used_for_checkpoint_selection':False,'autotune_uses_independent_probe_model':True,'seizure_centering_enabled':False};(out/'trace_clean_v1_protocol_audit.json').write_text(json.dumps(protocol,indent=2),encoding='utf8')
 for fold in tqdm(wanted,desc='TRACE-CLEAN-V1 outer folds',disable=not a.show_progress):
  test_keys=set(folds.loc[folds.outer_fold==fold,'patient_key']); development=[p for p in patients if p.patient_key not in test_keys]; test=[p for p in patients if p.patient_key in test_keys]; train,val=split(development,fold,a,existing);assert not ({p.patient_key for p in train}&{p.patient_key for p in val});assert not ({p.patient_key for p in train+val}&test_keys);inner=[x for x in inner if int(x['outer_fold'])!=int(fold)];inner += [{'patient_key':p.patient_key,'outer_fold':fold,'partition':'inner_train','outcome':p.outcome_success,'center':p.center} for p in train]+[{'patient_key':p.patient_key,'outer_fold':fold,'partition':'inner_validation','outcome':p.outcome_success,'center':p.center} for p in val];write_csv(manifest_path,pd.DataFrame(inner))
  fold_seed=a.seed+int(fold)-1;seed_all(fold_seed);probe=TRACERawMIL().to(device);a.current_train_window_batch_size=autotune(probe,train,device,a,fold_seed);del probe
  if device.type=='cuda':torch.cuda.empty_cache()
  seed_all(fold_seed);val_hash=hashlib.sha256('|'.join(sorted(p.patient_key for p in val)).encode()).hexdigest();model=TRACERawMIL().to(device);ema=ModelEMA(model,a.ema_decay);opt=torch.optim.AdamW(model.parameters(),lr=a.learning_rate,weight_decay=a.weight_decay);best_auc=-float('inf');best_bce=float('inf');best_epoch=0;patience=0;best_meta=None;cpdir=out/'checkpoints'/f'fold_{fold}';cpdir.mkdir(parents=True,exist_ok=True);expected_batches=int(np.ceil(len(train)/a.batch_size))
  print(f'model={MODEL}\nouter_fold={fold}\ndevelopment_train_n={len(train)}\ndevelopment_validation_n={len(val)}\nouter_test_n={len(test)}\nexpected_batches_per_epoch={expected_batches}\npatient_sampler=without_replacement\nrank_weight_epoch_1={rank_weight(1):.2f}\nrank_weight_epoch_3={rank_weight(3):.2f}\nrank_weight_epoch_5={rank_weight(5):.2f}\nrank_weight_epoch_6={rank_weight(6):.2f}\nrank_weight_epoch_10={rank_weight(10):.2f}\nlearning_rate={a.learning_rate}\nlr_scheduler=none\nema_decay={a.ema_decay}\nmax_epochs={a.max_epochs}\nearly_stopping_monitor=val_auroc\npatience={a.patience}\nhistorical_patient_identity_match_required=false',flush=True)
  epoch_progress=tqdm(range(1,a.max_epochs+1),desc=f'Fold {fold} epochs',disable=not a.show_progress)
  for epoch in epoch_progress:
   start=time.perf_counter();epoch_seed=fold_seed*100000+epoch*1000;ts=train_epoch(model,train,opt,ema,device,epoch_seed,a,epoch);rows,_=infer(ema.model,val,device,a.current_eval_window_batch_size,a.auto_window_batch_backoff,a.min_window_batch_size,a.vram_budget_fraction)
   if epoch==1:
    repeat,_=infer(ema.model,val,device,a.current_eval_window_batch_size,a.auto_window_batch_backoff,a.min_window_batch_size,a.vram_budget_fraction);difference=max(abs(x['logit']-y['logit']) for x,y in zip(rows,repeat))
    if difference>1e-7:raise RuntimeError(f'validation is non-deterministic: max logit difference={difference}')
   v=validation_statistics(rows);vf=pd.DataFrame(rows);metrics=metric_row(vf);probabilities=vf.probability_success.to_numpy(float);v.update({'validation_auroc':metrics['auroc'],'validation_success_auprc':metrics['success_auprc'],'validation_failure_auprc':metrics['failure_auprc'],'validation_balanced_accuracy':metrics['balanced_accuracy'],'validation_macro_f1':metrics['macro_f1'],'validation_probability_mean':float(probabilities.mean()),'validation_probability_std':float(probabilities.std())})
   if a.strict and epoch<=5 and rank_weight(epoch)!=0:raise RuntimeError('rank weight must be zero in epochs 1-5')
   saved=better_checkpoint(v['validation_auroc'],v['validation_bce'],best_auc,best_bce,a.min_delta)
   if saved:
    best_auc,best_bce,best_epoch,patience=v['validation_auroc'],v['validation_bce'],epoch,0;best_meta=state(ema.model,opt,fold,a,best_epoch,best_auc,best_bce,v,val_hash);torch.save(best_meta,cpdir/'best_val_auroc_ema.pt');torch.save(state(model,opt,fold,a,best_epoch,best_auc,best_bce,v,val_hash),cpdir/'best_val_auroc_raw.pt')
   else: patience+=1
   torch.save({'model_version':MODEL,'epoch':epoch,'model_state_dict':model.state_dict()},cpdir/'last_epoch_raw.pt');torch.save({'best_epoch':best_epoch,'best_val_auroc':best_auc,'best_val_bce':best_bce,'patience_counter':patience},cpdir/'training_state.pt')
   row={'outer_fold':fold,'epoch':epoch,'train_total_loss':ts.get('total'), 'train_bce':ts.get('bce'),'train_rank_raw':ts.get('rank_raw'),'lambda_rank':ts.get('rank_weight'),'train_rank_weighted':ts.get('rank_weighted'),'train_success_logit_mean':ts.get('success_logit_mean'),'train_failure_logit_mean':ts.get('failure_logit_mean'),'train_logit_std':ts.get('logit_std'),'best_validation_auroc_so_far':best_auc,'best_validation_bce_so_far':best_bce,'best_epoch_so_far':best_epoch,'patience_counter':patience,'checkpoint_saved':saved,'learning_rate':a.learning_rate,'gradient_norm':ts.get('gradient_norm'),'epoch_wall_time_seconds':time.perf_counter()-start,**v};history.append(row)
   epoch_progress.set_postfix(val_auroc=v['validation_auroc'],best_auroc=best_auc,patience=f'{patience}/{a.patience}')
   print(f'[TRACE-CLEAN-V1] fold={fold} epoch={epoch}/{a.max_epochs} train_unique_patients={ts["train_unique_patients"]} train_sampled_rows={ts["train_sampled_rows"]} train_batches={ts["train_batches"]} expected_train_batches={ts["expected_train_batches"]} duplicate_train_patients={ts["duplicate_train_patients"]} train_total={row["train_total_loss"]:.5f} train_bce={row["train_bce"]:.5f} train_rank_raw={row["train_rank_raw"]:.5f} lambda_rank={row["lambda_rank"]:.4f} train_rank_weighted={row["train_rank_weighted"]:.5f} val_bce={v["validation_bce"]:.5f} val_rank={v["validation_rank"]:.5f} val_selection={v["validation_selection_loss"]:.5f} val_auroc={v["validation_auroc"]:.6f} val_success_auprc={v["validation_success_auprc"]:.6f} val_failure_auprc={v["validation_failure_auprc"]:.6f} val_probability_mean={v["validation_probability_mean"]:.6f} val_probability_std={v["validation_probability_std"]:.6f} best_val_auroc={best_auc:.6f} best_epoch={best_epoch} patience={patience}/{a.patience} checkpoint_saved={"yes" if saved else "no"}',flush=True)
   if patience>=a.patience: break
  if best_meta is None: raise RuntimeError('validation AUROC is undefined; cannot select a checkpoint')
  chosen=torch.load(cpdir/'best_val_auroc_ema.pt',map_location=device,weights_only=False);ema.model.load_state_dict(chosen['model_state_dict']);print(f'[TRACE-CLEAN-V1][Fold {fold}] loading_best_checkpoint: epoch={chosen["best_epoch"]} val_auroc={chosen["best_val_auroc"]} val_bce={chosen["best_val_bce"]} val_rank={chosen["best_val_rank"]} val_selection={chosen["best_val_selection"]}',flush=True);rows,_=infer(ema.model,test,device,a.current_eval_window_batch_size,a.auto_window_batch_backoff,a.min_window_batch_size,a.vram_budget_fraction);frame=pd.DataFrame(rows);frame['outer_fold']=fold;frame['selected_epoch']=chosen['best_epoch'];frame['prediction_05']=(frame.probability_success>=.5).astype(int);oof.extend(frame.to_dict('records'));tm=metric_row(frame);test_probability_std=float(frame.probability_success.std(ddof=0));summaries.append({'outer_fold':fold,'selected_epoch':chosen['best_epoch'],'best_val_auroc':chosen['best_val_auroc'],'best_val_bce':chosen['best_val_bce'],**tm,'test_probability_std':test_probability_std});print(f'[TRACE-CLEAN-V1][Fold {fold}][TEST] selected_epoch={chosen["best_epoch"]} best_val_auroc={chosen["best_val_auroc"]} test_auroc={tm["auroc"]} test_failure_auprc={tm["failure_auprc"]} test_balanced_accuracy={tm["balanced_accuracy"]} test_macro_f1={tm["macro_f1"]} test_probability_std={test_probability_std}',flush=True)
 pred=pd.DataFrame(oof); assert not pred.patient_key.duplicated().any();write_csv(out/'training_history.csv',pd.DataFrame(history));write_csv(out/'trace_inner_validation_manifest.csv',pd.DataFrame(inner));write_csv(out/'oof_patient_predictions.csv',pred);write_csv(out/'fold_metrics.csv',pd.DataFrame(summaries));write_csv(out/'summary_metrics.csv',pd.DataFrame([metric_row(pred)]));write_csv(out/'bootstrap_ci.csv',bootstrap_ci(pred,2000,a.seed));(out/'TRACE_RAWMIL_CLEAN_V1_REPORT.md').write_text('TRACE_RAWMIL_CLEAN_V1; EMA checkpoint selection: validation AUROC, BCE tie-break only.\n');return 0
if __name__=='__main__':raise SystemExit(main())
