from __future__ import annotations
import argparse,hashlib,json,sys,time
from pathlib import Path
import numpy as np,pandas as pd,torch
PROJECT=Path(__file__).resolve().parents[2];REPO=PROJECT.parent
for p in (REPO,PROJECT):sys.path.insert(0,str(p))
from neuroez_c.task2.trace_dre_lite import MODEL_VERSION,CACHE_VERSION
from neuroez_c.task2.trace_dre_lite.schema import ViewConfig
from neuroez_c.task2.trace_dre_lite.cached_dataset import CachedCohort
from neuroez_c.task2.trace_dre_lite.model import TRACEDRELiteV2
from neuroez_c.task2.trace_dre_lite.trainer import seed_all,EMA,train_epoch,infer
from neuroez_c.task2.trace_dre_lite.evaluation import metric_row,bootstrap_ci
from neuroez_c.task2.trace_dre_lite.audit import model_audit
PROTOCOL='DIRECT_OUTER_5FOLD_FIXED_EPOCH'
def csv(path,data):
 p=Path(path);p.parent.mkdir(parents=True,exist_ok=True);tmp=p.with_suffix('.tmp');pd.DataFrame(data).to_csv(tmp,index=False);tmp.replace(p)
def js(path,data):
 p=Path(path);p.parent.mkdir(parents=True,exist_ok=True);tmp=p.with_suffix('.tmp');tmp.write_text(json.dumps(data,indent=2,default=str),encoding='utf8');tmp.replace(p)
def stable_hash(value):return hashlib.sha256(json.dumps(value,sort_keys=True,default=str).encode()).hexdigest()
def parse():
 p=argparse.ArgumentParser();p.add_argument('--cache-dir',required=True);p.add_argument('--fold-manifest',required=True);p.add_argument('--output-dir',required=True);p.add_argument('--fixed-epochs',type=int,default=10);p.add_argument('--max-epochs',type=int,help=argparse.SUPPRESS);p.add_argument('--patience',type=int,help='Ignored in direct-outer fixed-schedule mode');p.add_argument('--seed',type=int,default=42);p.add_argument('--folds',default='all');p.add_argument('--device',default='cuda');p.add_argument('--batch-size',type=int,default=4);p.add_argument('--gradient-accumulation-steps',type=int,default=2);p.add_argument('--learning-rate',type=float,default=2e-4);p.add_argument('--weight-decay',type=float,default=1e-3);p.add_argument('--gradient-clip',type=float,default=1.);p.add_argument('--ema-decay',type=float,default=.98);p.add_argument('--rank-weight',type=float,default=0.);p.add_argument('--n-deterministic-views',type=int,default=4);p.add_argument('--max-seizures-per-view',type=int,default=2);p.add_argument('--max-ez-channels-per-view',type=int,default=24);p.add_argument('--max-nez-channels-per-view',type=int,default=40);p.add_argument('--max-windows-per-phase',type=int,default=4);p.add_argument('--disable-side-features',action='store_true');p.add_argument('--disable-recruitment-dynamics',action='store_true');p.add_argument('--disable-propagation-escape',action='store_true');p.add_argument('--disable-virtual-disconnection',action='store_true');p.add_argument('--disable-cross-seizure-recurrence',action='store_true');p.add_argument('--enable-edge-correction',action='store_true');p.add_argument('--strict',action='store_true');p.add_argument('--smoke-test',action='store_true');p.add_argument('--no-resume-old-checkpoint',action='store_true');return p.parse_args()
def protocol_audit(folds,cohort,selected,fixed_epochs,smoke):
 keys=set(cohort.keys());mf=folds[folds.patient_key.isin(keys)].copy()
 if mf.patient_key.duplicated().any():raise RuntimeError('fold manifest contains duplicate patient records')
 if set(mf.patient_key)!=keys:raise RuntimeError('not every cache patient appears exactly once in fold manifest')
 all_test=set();rows=[]
 for fold in selected:
  test=set(mf[mf.outer_fold==fold].patient_key);train=keys-test
  if not test:raise RuntimeError(f'outer fold {fold} test is empty')
  labels=[cohort.load(k)['outcome_success'] for k in test]
  if not smoke and set(labels)!={0,1}:raise RuntimeError(f'outer fold {fold} lacks success or failure')
  if all_test&test:raise RuntimeError('outer test folds overlap')
  all_test|=test
  rows.append({'outer_fold':fold,'train_patient_ids_hash':stable_hash(sorted(train)),'test_patient_ids_hash':stable_hash(sorted(test)),'train_n':len(train),'test_n':len(test),'train_success':sum(cohort.load(k)['outcome_success'] for k in train),'train_failure':sum(1-cohort.load(k)['outcome_success'] for k in train),'test_success':sum(labels),'test_failure':sum(1-x for x in labels),'train_test_overlap_count':len(train&test)})
 if set(selected)==set(mf.outer_fold.unique()) and all_test!=keys:raise RuntimeError('five-fold test union does not equal complete cohort')
 return {'protocol':PROTOCOL,'n_outer_folds':5,'uses_inner_validation':False,'uses_nested_cv':False,'uses_early_stopping':False,'fixed_epochs':fixed_epochs,'final_model':'ema_final','outer_test_used_for_training':False,'outer_test_used_for_epoch_selection':False,'outer_test_used_for_hyperparameter_selection':False,'threshold':.5,'primary_metric':'pooled_oof_auroc','model_version':MODEL_VERSION,'cache_version':CACHE_VERSION,'folds':rows}
def main():
 a=parse();seed_all(a.seed)
 if a.patience is not None:print('patience is ignored in direct-outer fixed-schedule mode',flush=True)
 if a.max_epochs is not None:print('max-epochs is ignored; use --fixed-epochs',flush=True)
 started=time.time();root=Path(a.cache_dir);out=Path(a.output_dir);out.mkdir(parents=True,exist_ok=True);load_start=time.time();sig=json.loads((root/'cache_signature.json').read_text());cfg=ViewConfig(a.n_deterministic_views,a.max_seizures_per_view,a.max_ez_channels_per_view,a.max_nez_channels_per_view,a.max_windows_per_phase);cohort=CachedCohort(root,root/'cache_manifest.csv',a.seed,cfg);folds=pd.read_csv(a.fold_manifest);cache_load_seconds=time.time()-load_start;selected=sorted(folds.outer_fold.unique()) if a.folds=='all' else [int(x) for x in a.folds.split(',')];audit_protocol=protocol_audit(folds,cohort,selected,a.fixed_epochs,a.smoke_test);js(out/'direct_outer_protocol_audit.json',audit_protocol);device=torch.device(a.device if a.device!='cuda' or torch.cuda.is_available() else 'cpu');kwargs={k:getattr(a,k) for k in ('disable_side_features','disable_recruitment_dynamics','disable_propagation_escape','disable_virtual_disconnection','disable_cross_seizure_recurrence','enable_edge_correction')};probe=TRACEDRELiteV2(**kwargs);audit=model_audit(probe);js(out/'trace_dre_model_audit.json',audit);config={'model_version':MODEL_VERSION,'cache_version':CACHE_VERSION,'cache_signature':sig['signature_hash'],'seed':a.seed,'fixed_epochs':a.fixed_epochs,'learning_rate':a.learning_rate,'weight_decay':a.weight_decay,'ema_decay':a.ema_decay,'rank_weight':a.rank_weight,'view_config':cfg.__dict__,'model_kwargs':kwargs};config_hash=stable_hash(config);print(json.dumps({'protocol':PROTOCOL,'uses_inner_validation':False,'fixed_epochs':a.fixed_epochs,'final_model':'ema_final',**audit,'checkpoint_root':str(out/'checkpoints'/MODEL_VERSION/f'seed_{a.seed}')},indent=2),flush=True)
 allpred=[];history=[];summ=[];artifacts={k:[] for k in ('views','components','seizures','channels','vdr','vdr_nodes','recurrence')};view_audit=[];epoch_times=[];total_windows=0;mf=folds[folds.patient_key.isin(cohort.keys())]
 for fold in selected:
  test=sorted(mf[mf.outer_fold==fold].patient_key);train=sorted(set(cohort.keys())-set(test));print(f'[TRACE-DRE direct outer] fold={fold} train={len(train)} test={len(test)} fixed_epochs={a.fixed_epochs}',flush=True);model=TRACEDRELiteV2(**kwargs).to(device);ema=EMA(model,a.ema_decay);opt=torch.optim.AdamW(model.parameters(),lr=a.learning_rate,weight_decay=a.weight_decay)
  for epoch in range(1,a.fixed_epochs+1):
   stats=train_epoch(model,ema,cohort,train,opt,device,epoch,a);stats.update({'outer_fold':fold,'epoch':epoch,'learning_rate':opt.param_groups[0]['lr']});history.append(stats);epoch_times.append(stats['epoch_wall_time_seconds']);total_windows+=stats['n_windows_encoded'];print(f'[TRACE-DRE] fold {fold} epoch {epoch}/{a.fixed_epochs}: loss={stats["train_total"]:.5f} windows={stats["n_windows_encoded"]}',flush=True)
  cpdir=out/'checkpoints'/MODEL_VERSION/f'seed_{a.seed}'/f'fold_{fold}';cpdir.mkdir(parents=True,exist_ok=True);meta={'model_version':MODEL_VERSION,'cache_version':CACHE_VERSION,'evaluation_protocol':PROTOCOL,'outer_fold':fold,'seed':a.seed,'fixed_epochs':a.fixed_epochs,'uses_inner_validation':False,'uses_early_stopping':False,'outer_test_used_for_selection':False,'uses_true_ez_supernode':True,'virtual_disconnection_version':'TRUE_EZ_VDR_V1','model_kwargs':kwargs,'view_config':cfg.__dict__,'config_hash':config_hash};torch.save({**meta,'selected_model_type':'raw_final','state_dict':model.state_dict()},cpdir/'final_raw.pt');torch.save({**meta,'selected_model_type':'ema_final','state_dict':ema.model.state_dict()},cpdir/'final_ema.pt');ck=torch.load(cpdir/'final_ema.pt',map_location=device,weights_only=False)
  if ck['model_version']!=MODEL_VERSION or ck['cache_version']!=CACHE_VERSION or ck['config_hash']!=config_hash or not ck['uses_true_ez_supernode'] or ck['selected_model_type']!='ema_final':raise RuntimeError('final EMA checkpoint validation failed')
  final_model=TRACEDRELiteV2(**kwargs).to(device);final_model.load_state_dict(ck['state_dict']);pred,art=infer(final_model,cohort,test,device,a.n_deterministic_views)
  for x in pred:x['outer_fold']=fold
  for name,rows in art.items():
   for x in rows:x['outer_fold']=fold
   artifacts[name]+=rows
  allpred+=pred;metrics=metric_row(pd.DataFrame(pred));summ.append({'outer_fold':fold,'train_n':len(train),'test_n':len(test),'fixed_epochs':a.fixed_epochs,'selected_model_type':'ema_final','uses_inner_validation':False,'uses_early_stopping':False,'outer_test_inference_count':1,'test_auroc':metrics['auroc'],'test_accuracy':metrics['accuracy'],'test_balanced_accuracy':metrics['balanced_accuracy'],'test_macro_f1':metrics['macro_f1'],'test_brier':metrics['brier'],'test_success_auprc':metrics['success_auprc'],'loaded_checkpoint_path':str(cpdir/'final_ema.pt')});view_audit += [{'patient_key':k,'outer_fold':fold,'partition':'train' if k in train else 'test','n_views':a.n_deterministic_views} for k in train+test]
 pred=pd.DataFrame(allpred);fold_metrics=pd.DataFrame([{'outer_fold':f,**metric_row(g)} for f,g in pred.groupby('outer_fold')]);pooled=metric_row(pred);summary={**pooled,'fold_mean_auroc':fold_metrics.auroc.mean(),'fold_std_auroc':fold_metrics.auroc.std(ddof=0),'worst_fold_auroc':fold_metrics.auroc.min()};csv(out/'training_history.csv',history);csv(out/'training_summary.csv',summ);csv(out/'fold_metrics.csv',fold_metrics);csv(out/'summary_metrics.csv',[summary]);csv(out/'metrics_by_center.csv',[{'center':c,**metric_row(g)} for c,g in pred.groupby('center')]);csv(out/'bootstrap_ci.csv',bootstrap_ci(pred,2000,a.seed));csv(out/'oof_patient_predictions.csv',pred);csv(out/'view_level_predictions.csv',artifacts['views']);csv(out/'patient_component_scores.csv',artifacts['components']);csv(out/'seizure_component_scores.csv',artifacts['seizures']);csv(out/'channel_escape_scores.csv',artifacts['channels']);csv(out/'virtual_disconnection_scores.csv',artifacts['vdr']);csv(out/'virtual_disconnection_node_audit.csv',artifacts['vdr_nodes']);csv(out/'cross_seizure_recurrence.csv',artifacts['recurrence']);runtime={'cache_load_seconds':cache_load_seconds,'cpu_preprocessing_seconds_during_training':0.,'n_windows_encoded':total_windows,'windows_per_second':total_windows/max(sum(epoch_times),1e-9),'gpu_peak_allocated_gb':torch.cuda.max_memory_allocated(device)/2**30 if device.type=='cuda' else 0.,'gpu_peak_reserved_gb':torch.cuda.max_memory_reserved(device)/2**30 if device.type=='cuda' else 0.,'epoch_wall_time_seconds':epoch_times,'total_wall_time_seconds':time.time()-started};js(out/'runtime_profile.json',runtime);(out/'TRACE_DRE_LITE_V2_1_DIRECT_OUTER_REPORT.md').write_text(f'{MODEL_VERSION} direct outer fixed-epoch evaluation.\n',encoding='utf8');return 0
if __name__=='__main__':raise SystemExit(main())
